CREATE TABLE [dbo].[Employees]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FirstName] NVARCHAR(50) NOT NULL, 
    [LastName] NVARCHAR(50) NOT NULL, 
    [Pin] NVARCHAR(4) NOT NULL, 
    [IsClockedIn] BIT NOT NULL DEFAULT 0
)
